version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: cronitor-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cronitor"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cronitor-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mailpit:
    image: axllent/mailpit
    container_name: cronitor-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped


  frontend:
    container_name: cronitor-frontend
    build:
      context: ./frontend    # Points to your frontend folder containing its Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development


  backend:
    container_name: cronitor-backend
    build:
      context: .             # Points to the root (or ./backend if it's in a subdirectory)
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: